min_mainnet_k_size: 29

# Send a ping to all peers after ping_interval seconds
ping_interval: 120
self_hostname: &self_hostname "localhost"
prefer_ipv6: False
daemon_port: 56920
daemon_max_message_size: 50000000 # maximum size of RPC message in bytes
inbound_rate_limit_percent: 100
outbound_rate_limit_percent: 30

network_overrides: &network_overrides
  constants:
    mainnet:
      NETWORK_TYPE: 0
      GENESIS_CHALLENGE: 69cfa80789667c51428eaf2f2126e6be944462ee5b59b8128e90b9a650f865c1
      GENESIS_PRE_FARM_POOL_PUZZLE_HASH: "1a86fab63fc8f4fcfe1708b85c56e0ef9d70ca17278e6c15f9713b148ecf920a"
      GENESIS_PRE_FARM_FARMER_PUZZLE_HASH: "5b848b19bd465b2edf93428e553bfeafcee17699cce5fbc3587fc281c2ac17d4"
      GENESIS_PRE_FARM_COMMUNITY_PUZZLE_HASH: "4e7d87c3752c0b4a1f25ec7ac5c10f347c39406e6753220043f28e5a450e0388"
    testnet0:
      DIFFICULTY_CONSTANT_FACTOR: 10052721566054
      GENESIS_CHALLENGE: 117816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015af
      GENESIS_PRE_FARM_FARMER_PUZZLE_HASH: 5b848b19bd465b2edf93428e553bfeafcee17699cce5fbc3587fc281c2ac17d4
      GENESIS_PRE_FARM_POOL_PUZZLE_HASH: 1a86fab63fc8f4fcfe1708b85c56e0ef9d70ca17278e6c15f9713b148ecf920a
      MIN_PLOT_SIZE: 18
      NETWORK_TYPE: 1
      MEMPOOL_BLOCK_BUFFER: 10
      EPOCH_BLOCKS: 768
      DIFFICULTY_STARTING: 1
  config:
    mainnet:
      address_prefix: "xcc"
      default_full_node_port: 9699
    testnet0:
      address_prefix: "txcc"
      default_full_node_port: 59699

selected_network: &selected_network "mainnet"
ALERTS_URL: https://download.chivescoin.org/notify/mainnet_alert.txt
CHIVES_ALERTS_PUBKEY: 89b7fd87cb56e926ecefb879a29aae308be01f31980569f6a75a69d2a9a69daefd71fb778d865f7c50d6c967e3025937

# public ssl ca is included in source code
# Private ssl ca is used for trusted connections between machines user owns
private_ssl_ca:
  crt: "config/ssl/ca/private_ca.crt"
  key: "config/ssl/ca/private_ca.key"

chives_ssl_ca:
  crt: "config/ssl/ca/chives_ca.crt"
  key: "config/ssl/ca/chives_ca.key"


daemon_ssl:
  private_crt: "config/ssl/daemon/private_daemon.crt"
  private_key: "config/ssl/daemon/private_daemon.key"


# Controls logging of all servers (harvester, farmer, etc..). Each one can be overriden.
logging: &logging
  log_stdout: False  # If True, outputs to stdout instead of a file
  log_filename: "log/debug.log"
  log_level: "WARNING"  # Can be CRITICAL, ERROR, WARNING, INFO, DEBUG, NOTSET
  log_maxfilesrotation: 7 #  Max files in rotation. Default value 7 if the key is not set
  log_syslog: False  # If True, outputs to SysLog host and port specified
  log_syslog_host: "localhost"  # Send logging messages to a remote or local Unix syslog
  log_syslog_port: 514  # UDP port of the remote or local Unix syslog


ui:
   # The ui node server (if run) will run on this port
  port: 8242

  # Which port to use to communicate with the full node
  rpc_port: 9775

  # This SSH key is for the ui SSH server
  ssh_filename: config/ssh_host_key
  logging: *logging
  network_overrides: *network_overrides
  selected_network: *selected_network

  # this is where the electron UI will find its daemon
  # defaults to the one running locally with its private keys
  daemon_host: *self_hostname
  daemon_port: 56920
  daemon_ssl:
    private_crt: config/ssl/daemon/private_daemon.crt
    private_key: config/ssl/daemon/private_daemon.key

wallet:
  port: 9669
  rpc_port: 9876

  enable_profiler: False

  # see description for full_node.db_sync
  db_sync: auto
  # Allow connecting to remote peers for sync
  connect_to_unknown_peers: True
  # The minimum height that we care about for our transactions. Set to zero
  # If we are restoring from private key and don't know the height.
  starting_height: 0
  start_height_buffer: 100  # Wallet will stop fly sync at starting_height - buffer
  num_sync_batches: 50
  initial_num_public_keys: 100
  initial_num_public_keys_new_wallet: 5

  full_node_peer:
    host: *self_hostname
    port: 9699

  testing: False
  database_path: wallet/db/blockchain_wallet_v1_CHALLENGE_KEY.sqlite
  wallet_peers_path: wallet/db/wallet_peers.dat

  logging: *logging
  network_overrides: *network_overrides
  selected_network: *selected_network

  target_peer_count: 5
  peer_connect_interval: 60
  # The introducer will only return peers who it has seen in the last
  # recent_peer_threshold seconds
  recent_peer_threshold: 6000

  introducer_peer:
    host: introducer.chivescoin.org # Chives AWS introducer IPv4/IPv6
    port: 9699

  dns_servers:
    - "dns-introducer.chivescoin.org"

  ssl:
    private_crt:  "config/ssl/wallet/private_wallet.crt"
    private_key:  "config/ssl/wallet/private_wallet.key"
    public_crt:  "config/ssl/wallet/public_wallet.crt"
    public_key:  "config/ssl/wallet/public_wallet.key"

  trusted_peers:
    trusted_node_1: "config/ssl/full_node/public_full_node.crt"

  short_sync_blocks_behind_threshold: 20
